services:
###########################
# Setup the PHP container
###########################
    linux_agcc:
        container_name: ${NAME_PROJECT}_gcc
        restart: always
        build:
            context: ./.docker/images/linux_agcc/
            args:
                - VALUE_GCC_VERSION=${VALUE_GCC_VERSION}
        tty: true
        stdin_open: true
        volumes:
            - ./project:/home/project:rw
